- crates/hir_ty/src/ty/pretty.rs
If you paste the following PoC into a WGSL file in VS Code with wgsl-analyzer installed, `&foo[0]` is highlighted with the confusing tooltip `expected ptr<i32>, found ptr<i32>`:
```wgsl
var<storage, read_write> foo: array<i32>;
let bar: ptr<storage, i32, read_write> = &foo[0];
```
The type is mismatched only because the storage class doesn't match (expected `storage` vs actual `private`). (Ironically, this mismatch is due to [a TODO item](https://github.com/wgsl-analyzer/wgsl-analyzer/blob/72fee945af9134b3abae9962a774ebba2a2601f4/crates/hir_ty/src/infer.rs#L640) where array indexes are always inferred to be of storage class `private`, something I might make yet another pull request for.)
This pull request modifies `hir_ty::ty::pretty::write_ty` to display the storage class and access mode …
> Include storage class and access mode in the pretty print for `ref` and `ptr` types

- README.md
Without this 2 character change, the setup function errors out.
> Fixed README: for nvim lsp setup, wgsl_analyzer.setup must take table param

- README.md
The people on the wesl server created a new discord server for this extension. This pr adds a badge to the readme to link to that server.
https://discord.com/invite/dZJ3JTbhaU
> add link to discord server for this extension to README

- README.md
I just noticed the Emacs `init.el` code block was missing the closing delimiter, causing the rest of the README to be missing it's formatting when viewed on GitHub.
> Close code block in README.md

- .github/workflows/release.yml
newer MacOS machines run on Aarch64 instead of x64_86 which caused the bug. I also added the `workflow_dispatch` thingy to manually test the run. I think it's worth keeping.
> Fix CI run on MacOS

- Cargo.lock
- crates/base_db/src/change.rs
- crates/base_db/src/input.rs
- crates/base_db/src/lib.rs
- crates/hir/Cargo.toml
- crates/hir/src/lib.rs
- crates/hir_def/Cargo.toml
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/db.rs
- crates/hir_def/src/hir_file_id.rs
- crates/hir_def/src/module_data/lower.rs
- crates/hir_def/src/resolver.rs
- crates/ide/src/db.rs
- crates/ide/src/hover.rs
- crates/ide/src/lib.rs
- crates/ide/src/tests.rs
- crates/wgsl_analyzer/src/bin/main.rs
- crates/wgsl_analyzer/src/config.rs
- crates/wgsl_analyzer/src/diagnostics.rs
- crates/wgsl_analyzer/src/global_state.rs
- crates/wgsl_analyzer/src/handlers.rs
- crates/wgsl_analyzer/src/lib.rs
- crates/wgsl_analyzer/src/lsp_ext.rs
- crates/wgsl_analyzer/src/main_loop.rs
- crates/wgsl_analyzer/src/reload.rs
- crates/wgsl_parser/src/syntax_kind.rs
- crates/wgsl_parser/src/tests.rs
- editors/code/src/ctx.ts
- editors/code/src/lsp_ext.ts
Rebase on `main` and fix up errors from https://github.com/wgsl-analyzer/wgsl-analyzer/pull/82.
There were also some warnings & lint issues to fix.
There was also a change to the AST parser that broke imports that we need to revert: [ fix ](https://github.com/wgsl-analyzer/wgsl-analyzer/issues/100) by reverting https://github.com/wgsl-analyzer/wgsl-analyzer/commit/ea2c51e73df0fa9ca45d8bb2b4851b2ec70bd08d & this means changing some of the test assertions regarding the AST.
Relative imports should now work, like so
```
#import "../../shared/core-structs.wgsl"
```
> Rebase support-input-paths on main

- flake.nix
Nix flake is broken by https://github.com/wgsl-analyzer/wgsl-analyzer/pull/176 as it references an undefined variable.
If you are fixing a specific issue, simply say "Fixes #X".
Set the correct variable name.
- Did you test these changes? If so, how?
- Are there any parts that need more testing?
- How can other people (reviewers) test your changes? Is there anything specific they need to know?
- If relevant, what platforms did you test these changes on, and are there any important ones you cannot test?
This section is optional. If this PR does not include a visual change or does not add a new feature, you can delete this section.
- Help others understand the result of this PR by showcasing your awesome work!
- If this PR adds a new feature or public API, consider adding a brief …
> Fix flake package variable

- editors/code/language-configuration.json
This extension has the same issue as described [here](https://github.com/PolyMeilex/vscode-wgsl/issues/20). This PR is a port of the fix that was eventually applied to `vscode-wgsl`.
Remove the angle brackets from the language configuration file. This may affect highlighting of angle brackets when the cursor is on one side of a pair of angle brackets, but the red highlighting of other uses of angle brackets (return syntax, comparison operations) will no longer be present.
- Did you test these changes? If so, how?
- Are there any parts that need more testing?
- How can other people (reviewers) test your changes? Is there anything specific they need to know?
- If relevant, what platforms did you test these changes on, and are there any important ones you cannot test?
This section is …
> Fix red highlighting of angle brackets when not part of a bracket.

- Cargo.lock
- crates/edition/Cargo.toml
- crates/edition/src/lib.rs
Add a crate to provide an enum for "editions" of the language being analyzed.
This can be expanded upon and used to support different versions of the WGSL specification (maybe once stability is a major concern) and also to support extension to the language such as WESL and extensions thereupon.
This will also make it simpler to port and update other crates from r-a because there is something to fill that gap, even if it isn't very useful at the moment.
The first crate that will use this is an update to `crates/parser`.
`xtask` may also use it in the future in order to generate documentation about lints (after wgsl lints become a feature)
Contributes to #182 
Port edition crate from r-a
N/A
> add edition crate

- Cargo.toml
- crates/stdx/src/anymap.rs
- crates/stdx/src/process.rs
- crates/wgsl-analyzer/src/bin/main.rs
- crates/wgsl-analyzer/src/dispatch.rs
- crates/wgsl-analyzer/src/handlers/notification.rs
- crates/wgsl-analyzer/src/line_index.rs
- crates/wgsl-analyzer/src/lsp/capabilities.rs
- crates/wgsl-analyzer/src/main_loop.rs
- xtask/src/tidy.rs
Clean code, follow best practices using lints
- Remove irrelevant stuff from Cargo.toml
- Add unsafe safety documentation.
- Fix Cargo.toml formatting to not cause Even Better TOML to crash
- Fix some other small lints
CI
> internal: Cleanup Cargo.toml, add safety comments, follow more lints

- crates/syntax/src/ast.rs
- crates/wgsl-analyzer/src/handlers/notification.rs
- crates/wgsl_formatter/src/lib.rs
- crates/wgsl_formatter/src/tests.rs
- Fixes #121: Struct definitions are now properly formatted by wgslfmt with consistent indentation of the opening brace, each field, and the closing brace.
- Fixes #283, the “unexpected DidChangeTextDocument” error by populating state.mem_docs on document open and re-enabling VFS updates on change. This needed to be fixed because if you open an unformatted file, format it, then keep pressing format, then it will delete some of your work because the file does not become updated in the vfs without this fix
- Updated the SyntaxKind::StructDeclaration arm in format_syntax_node to use these helpers for the {, each field’s first token, and the }
- In ```handle_did_open_text_document```, now insert the new document into state.mem_docs so that subsequent change notifications find an entry.
- …
> add struct field formatting

- crates/wgsl-analyzer/src/dispatch.rs
- crates/wgsl-analyzer/src/handlers/request.rs
- crates/wgsl-analyzer/src/lsp/capabilities.rs
- crates/wgsl-analyzer/src/main_loop.rs
Fixes #260 
- Added diagnostics to server capabilities
- added request handler
Opened a wgsl file and added syntax errors, e.g. this error successfully appears:
```wgsl
fn f() {
let x: = 92;
}
```
There are some errors it doesn't catch like missing semicolons but not sure if that's due to the backend? I can't remember if it caught those types of errors.
> add diagnostics back to frontend

- editors/code/syntaxes/wesl.tmLanguage.json
Add syntax highlighting for the WESL import statement.
Describe the solution used to achieve the objective above.
I originally thought that I'd have to do more complex stuff like in https://github.com/Geri-Borbas/VSCode.Extension.eppz_Code/blob/master/syntaxes/source.cs.extensions.json , but it turned out to be really straightforward.
I manually tested it with strings like `import self::foo::{bar as baz, nya};`, and with the "inspect scopes" command.
Ignore the squiggly red line.
> Add WESL syntax highlighting

- editors/code/syntaxes/wesl.tmLanguage.json
- editors/code/syntaxes/wgsl.tmLanguage.json
Improve syntax highlighting
Improve highlighting for matrix and vector types.
Specify some keywords as control keywords.
Clean up other definitions.
Add predefined enums.
Mark preprocessor as deprecated.
Tested locally
> feature: Update tm language

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
Weekly CI works as intended. Step names make sense.
Fix rustflags in weekly.yaml and improve step names.
https://github.com/wgsl-analyzer/wgsl-analyzer/actions/runs/16816359056/job/47634000385
> CI improvements

- editors/code/package.json
Fixes #446
Remove non-existent command.
The syntax tree views and command can be ported from r-a in a follow-up.
Tested locally
> Remove `wgsl-analyzer.syntaxTree`

- .github/workflows/release.yaml
Fixes broken release workflow due to 1.89 update
Use dtolnay/rust-toolchain in release workflow
TODO
> Use dtolnay/rust-toolchain in release workflow

- Cargo.lock
- Cargo.toml
- crates/wgsl-analyzer/src/bin/main.rs
I noticed that the regex dependency got compiled. Which hurts my compile times.
We can disable the `env-filter` feature from tracing-subscriber. Apparently the `setup_logging` function is no longer being used.
> Remove unused env-filter feature

- Cargo.lock
- Cargo.toml
- crates/base_db/Cargo.toml
- crates/hir/Cargo.toml
- crates/hir_def/Cargo.toml
- crates/hir_ty/Cargo.toml
- crates/ide-db/Cargo.toml
- crates/ide/Cargo.toml
- crates/ide_completion/Cargo.toml
- crates/parser/Cargo.toml
- crates/profile/Cargo.toml
- crates/stdx/Cargo.toml
- crates/syntax/Cargo.toml
- crates/test-utils/Cargo.toml
- crates/toolchain/Cargo.toml
- crates/vfs-notify/Cargo.toml
- crates/wgsl-analyzer/Cargo.toml
- crates/wgsl-analyzer/src/bin/main.rs
- crates/wgsl-analyzer/src/tracing/config.rs
- crates/wgsl_formatter/Cargo.toml
- crates/wgslfmt/Cargo.toml
- xtask/Cargo.toml
Dependabot cannot keep workspace dependencies up to date, and we want Dependabot to keep our dependencies up to date.
https://github.com/dependabot/dependabot-core/issues/7896
This PR works around that by not using workspace dependencies in most cases. The versions will naturally be in sync because we have `cargo deny` for denying multiple versions of the same dependency in the tree and Dependabot will update all files at once.
Note that this can be undone using https://mainmatter.com/blog/2024/03/18/cargo-autoinherit/ in the future when the Dependabot bug is fixed.
> Use local dependencies instead of workspace dependencies

- .github/workflows/ci.yaml
CI is fast and doesn't waste resources.
Copy CI from the taplo repository itself.
Should bring this step down from a few minutes down to a few seconds.
Before
After
> internal: Speed up toml CI check using Docker image

- .github/workflows/ci.yaml
cargo-udeps takes a long time to build and it is unnecessary for this check
This install action uses binstall to install a tool from GitHub Releases. I see it used in other projects.
Tested in CI
Before
After
> internal: Install cargo-udeps from GitGub Releases instead of building it

- Cargo.toml
- crates/base_db/Cargo.toml
- crates/edition/Cargo.toml
- crates/hir/Cargo.toml
- crates/hir_def/Cargo.toml
- crates/hir_ty/Cargo.toml
- crates/ide-db/Cargo.toml
- crates/ide/Cargo.toml
- crates/ide_completion/Cargo.toml
- crates/parser/Cargo.toml
- crates/profile/Cargo.toml
- crates/stdx/Cargo.toml
- crates/syntax/Cargo.toml
- crates/test-utils/Cargo.toml
- crates/toolchain/Cargo.toml
- crates/vfs-notify/Cargo.toml
- crates/wgsl-analyzer/Cargo.toml
- crates/wgsl_formatter/Cargo.toml
Tombi keeps shouting at me because it doesn't like our `Cargo.toml` files. Turns out that they have a point.
The authors field is deprecated. https://doc.rust-lang.org/cargo/reference/manifest.html#the-authors-field
And the order in which we defined tables is discouraged by the toml specification.
> Defining tables out-of-order is discouraged.
> https://toml.io/en/v1.0.0#table
I removed the authors field, and moved the offending table further down.
- Dear CI, please be green
Zero warnings, even with tombi installed :)
> Toml fixes
