crates/hir_ty/builtins.wgsl
=> Fix value-testing builtins to return bool [PR#7]

crates/hir/src/diagnostics/mod.rs, crates/hir/src/lib.rs, crates/hir_def/src/data.rs, crates/hir_def/src/db.rs, crates/hir_def/src/module_data/lower.rs, crates/hir_def/src/module_data/mod.rs, crates/hir_def/src/module_data/pretty.rs, crates/hir_def/src/resolver.rs, crates/hir_ty/src/infer.rs, crates/hir_ty/src/ty.rs, crates/hir_ty/src/ty/pretty.rs, crates/ide/src/goto_definition.rs, crates/ide_completion/src/completions/expr.rs, crates/ide_completion/src/item.rs, crates/syntax/src/ast.rs, crates/wgsl_analyzer/src/to_proto.rs, crates/wgsl_parser/src/grammar/mod.rs, crates/wgsl_parser/src/syntax_kind.rs, crates/wgsl_parser/src/tests.rs
Got to admit, I don't understand all of this, but it seems to work now :)
I did the alias "unwrapping" inside `expect_ty_inner`... maybe it would be better to do it some earlier point?
=> Support type aliasing

crates/wgsl_formatter/src/lib.rs, crates/wgsl_formatter/src/tests.rs, crates/wgslfmt/src/main.rs
Fixing merge conflicts of #119
=> Pd3 p configurable indent symbol

.github/workflows/release.yml, tools/src/bin/package.rs
=> Remove win32-ia32 target

.github/workflows/ci.yml, .github/workflows/weekly.yml, crates/base_db/src/line_index.rs, crates/base_db/src/shader_processor.rs, crates/hir_ty/src/ty.rs, crates/wgsl_analyzer/src/dispatch.rs, crates/wgsl_analyzer/src/lsp_utils.rs, crates/wgsl_parser/src/syntax_kind.rs
Fixes #160
Follow clippy lints, some expect, allow shenanigans were necessary
Fix the check-doc weekly CI copy paste error
Tested nightly ci commands locally
https://github.com/wgsl-analyzer/wgsl-analyzer/actions/runs/13360922201
deadlinks error will be addressed in #166
=> fix nightly/beta

crates/stdx/src/assert.rs, crates/stdx/src/lib.rs
add assertion utility
ripped from #177 
Copy from r-a
CI
=> add assert to stdx

crates/ide/src/db.rs, crates/ide/src/diagnostics.rs, crates/ide/src/lib.rs, crates/ide_completion/src/config.rs, crates/ide_completion/src/context.rs, crates/ide_completion/src/lib.rs, crates/stdx/src/lib.rs, crates/wgsl-analyzer/src/handlers.rs, crates/wgsl-analyzer/src/lib.rs
pull the ide and ide_completion stuff from #177
=> Update ide and ide_completion

.github/workflows/release.yml
Fixes #164 
Add job to release CI
TODO
TODO
=> Publish to OVSX

docs/book/src/other_editors.md
Fixes #133 
Document the level of current support.
Open a new issue for the feature request @ #207 
N/A
=> Document IntelliJ IDE support

.github/workflows/release.yml
=> add permission to publish stage

editors/code/.vscodeignore
Fix the bug with syntax highlighting not working
Re-exclude syntaxes folder in .vscodeignore
=> fix syntax highlighting

Cargo.lock, Cargo.toml, crates/hir_def/src/expression.rs, crates/parser/Cargo.toml, crates/parser/src/grammar/expression.rs, crates/parser/src/lib.rs, crates/parser/src/syntax_kind.rs, crates/parser/src/tests.rs, crates/syntax/src/ast.rs, xtask/src/utilities.rs
Follow spec closely and have comprehensive tests
Split IntLiteral definition, renamings, and add tests based on spec sheet
Added tests, will run in CI
=> Parser improvements

docs/book/src/contributing/lsp-extensions.md, editors/code/package.json, xtask/src/distribute.rs, xtask/src/tidy.rs
update package.json with aspirational config and remove some incorrect info
fix cargo xtask tidy
=> Improve package.json

xtask/src/publish.rs
Fix `cargo xtask release` command
Rename branch
Tested locally
=> fix xtask release

.github/workflows/ci.yml, .github/workflows/dependencies.yml
Prevents #252 from happening again while keeping the toolchain pinned.
Use stable with a specific toolchain
=> specify toolchain

crates/hir/src/diagnostics/global_variable.rs, crates/hir/src/diagnostics/mod.rs, crates/hir_def/src/body/lower.rs, crates/hir_def/src/data.rs, crates/hir_def/src/expression.rs, crates/hir_def/src/module_data/lower.rs, crates/hir_def/src/module_data/mod.rs, crates/hir_def/src/type_ref.rs, crates/hir_ty/build.rs, crates/hir_ty/src/db.rs, crates/hir_ty/src/infer.rs, crates/hir_ty/src/ty.rs, crates/hir_ty/src/ty/pretty.rs, crates/hir_ty/src/validate.rs, crates/ide/src/diagnostics.rs, crates/parser/src/grammar.rs, crates/syntax/src/ast.rs
Terminology should be discoverable and match the spec
Rename `StorageClass` to `AddressSpace`
https://www.w3.org/TR/WGSL/#address-spaces-storage
CI
=> Rename `StorageClass` to `AddressSpace`

crates/hir_def/src/type_ref.rs
Fixes a small error caught by clippy
TODO: Tests!
=> Fix error in matrix dimentions mapping

Cargo.lock, crates/hir_def/src/body.rs, crates/ide-db/src/lib.rs, crates/ide/src/lib.rs, crates/wgsl-analyzer/src/handlers/request.rs, crates/wgsl-analyzer/src/lsp/to_proto.rs
Fix the highlight being on the definition rather than the hovered item.
Use old constructor. Need to investigate why the new function isn't working.
Manually tested
=> Fix goto definition

.github/workflows/dependabot-autofix.yaml
=> Fix autofix workflow #2

.github/workflows/dependabot-autofix.yaml
=> Add contents: write permission to autofix

docs/book/src/other_editors.md
Updates the nvim sections in `other_editors.md`, more specifically adding instructions for a setup with cmp and adding to the file types section.
=>  Add nvim cmp section, Update nvim section

.github/workflows/ci.yaml, .github/workflows/dependabot-autofix.yaml, .github/workflows/dependencies.yaml, Cargo.toml, crates/hir_def/src/database.rs, crates/hir_ty/src/database.rs
=> internal: bump rust to 1.89.0

crates/base_db/Cargo.toml, crates/base_db/src/shader_processor.rs
Fixes #464 
Enable unicode feature
Added unit test
=> Fix regex compilation

.github/workflows/ci.yaml, .github/workflows/dependabot-autofix.yaml, .github/workflows/dependencies.yaml, Cargo.toml, crates/hir_def/src/database.rs, crates/wgsl_formatter/src/lib.rs
Fixes #450
Remove unfulfilled `expect`s
https://github.com/wgsl-analyzer/wgsl-analyzer/actions/runs/16816798174
=> internal: Update to rust 1.90 toolchain
